### ISSUE TITLE
Velocity can't use 25565 port and viaversion not loaded

### ISSUE THREAD

**Issue by candy999** [RelativityMC/raknetify#20]
**Describe the bug**
Couldn't pass ProxyInitializeEvent to viaversion
java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
and 25565: Address already in use: bind

**To Reproduce**
1. Do something
2. See error

**Expected behavior**

**Screenshots**

**Runtime info (please complete the following information):**
 - OS: windows server 2022
 - Minecraft version: 1.19.3
 - Mod version: raknetify-fabric-0.1.0+alpha.5.32-all
 - Mod branch: (fill this if you are not using the default `ver` branches)
![image](https://user-images.githubusercontent.com/2743971/210815875-b518d05c-b7a9-4d69-8533-4dfacd8078ed.png)

**Crash reports / logs**

[23:12:53 INFO]: Booting up Velocity 3.1.2-SNAPSHOT (git-c9e0e14e-b201)...
[23:12:53 INFO]: Loading localizations...
[23:12:53 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[23:12:53 INFO]: Loading plugins...
[23:12:53 INFO]: Loaded plugin geyser 2.1.0-SNAPSHOT (git-master-1b4be61) by GeyserMC
[23:12:53 INFO]: Loaded plugin luckperms 5.4.56 by Luck
[23:12:53 INFO]: Loaded plugin raknetify 0.1.0+alpha.5.32 by ishland
[23:12:53 INFO]: Loaded plugin viaversion 4.5.2-SNAPSHOT by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv [23:12:53 INFO]: Loaded plugin viabackwards 4.5.2-SNAPSHOT by Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1
[23:12:53 INFO]: Loaded 5 plugins
[23:12:54 INFO]:         __
[23:12:54 INFO]:   |    |__)   LuckPerms v5.4.56
[23:12:54 INFO]:   |___ |      Running on Velocity - Velocity
[23:12:54 INFO]:
[23:12:54 INFO] [luckperms]: Loading configuration...
[23:12:54 INFO] [luckperms]: Loading storage provider... [H2]
[23:12:54 INFO] [luckperms]: Loading internal permission managers...
[23:12:54 INFO] [luckperms]: Performing initial data load...
[23:12:54 INFO] [luckperms]: Successfully enabled. (took 1015ms)
[23:12:55 INFO] [geyser]: Loading extensions...
[23:12:55 INFO] [geyser]: Loaded 0 extension(s)
[23:12:55 INFO] [raknetify]: Bootstrapping raknetify in wrapped environment
[23:12:55 ERROR]: Couldn't pass ProxyInitializeEvent to viaversion
java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.viaversion.viaversion.api.Via.manager(Via.java:84) ~[?:?]
        at com.viaversion.viaversion.api.Via.getPlatform(Via.java:64) ~[?:?]
        at com.viaversion.viaversion.configuration.AbstractViaConfig.lambda$loadBlockedProtocolVersions$0(AbstractViaConfig.java:216) ~[?:?]
        at com.viaversion.viaversion.libs.fastutil.ints.IntCollection.removeIf(IntCollection.java:285) ~[?:?]
        at com.viaversion.viaversion.configuration.AbstractViaConfig.loadBlockedProtocolVersions(AbstractViaConfig.java:213) ~[?:?]
        at com.viaversion.viaversion.configuration.AbstractViaConfig.loadFields(AbstractViaConfig.java:135) ~[?:?]
        at com.viaversion.viaversion.velocity.platform.VelocityViaConfig.loadFields(VelocityViaConfig.java:43) ~[?:?]
        at com.viaversion.viaversion.configuration.AbstractViaConfig.reloadConfig(AbstractViaConfig.java:102) ~[?:?]
        at com.viaversion.viaversion.velocity.platform.VelocityViaConfig.<init>(VelocityViaConfig.java:38) ~[?:?]
        at com.viaversion.viaversion.VelocityPlugin.onProxyInit(VelocityPlugin.java:102) ~[?:?]
        at com.viaversion.viaversion.Lmbda$8.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:12:55 ERROR]: Couldn't pass ProxyInitializeEvent to viabackwards
java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.viaversion.viaversion.api.Via.manager(Via.java:84) ~[?:?]
        at com.viaversion.viaversion.api.Via.getManager(Via.java:50) ~[?:?]
        at com.viaversion.viabackwards.VelocityPlugin.onProxyStart(VelocityPlugin.java:56) ~[?:?]
        at com.viaversion.viabackwards.Lmbda$9.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:12:55 ERROR]: Couldn't pass ProxyInitializeEvent to viaversion
java.lang.IllegalArgumentException: ViaVersion has not loaded the platform yet
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.viaversion.viaversion.api.Via.manager(Via.java:84) ~[?:?]
        at com.viaversion.viaversion.api.Via.getManager(Via.java:50) ~[?:?]
        at com.viaversion.viaversion.VelocityPlugin.onProxyLateInit(VelocityPlugin.java:117) ~[?:?]
        at com.viaversion.viaversion.Lmbda$7.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-c9e0e14e-b201)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:12:55 INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565
[23:12:55 INFO] [geyser]: ******************************************
[23:12:55 INFO] [geyser]:
[23:12:55 INFO] [geyser]: 正在載入 Geyser 版本 2.1.0-SNAPSHOT (git-master-1b4be61)
[23:12:55 INFO] [geyser]:
[23:12:55 INFO] [geyser]: ******************************************
[23:12:55 INFO]: Listening for GS4 query on /[0:0:0:0:0:0:0:0]:25565
[23:12:55 INFO]: Done (2.88s)!
>
[23:12:58 INFO] [geyser]: Geyser 在 0.0.0.0:19132 啟動
[23:12:58 INFO] [geyser]: 完成 (2.5s)！ 執行 /geyser help 來取得說明！
[23:12:58 ERROR] [raknetify]: Raknetify server failed to start on /127.0.0.1:25565: Address already in use: bind
[23:12:58 ERROR] [raknetify]: Raknetify server failed to start on /[0:0:0:0:0:0:0:1]:25565: Address already in use: bind
[23:12:58 ERROR] [raknetify]: Raknetify server failed to start on /172.27.157.85:25565: Address already in use: bind
[23:12:58 ERROR] [raknetify]: Raknetify server failed to start on /[fe80:0:0:0:bc6b:28a2:e74d:eed2%eth0]:25565: Address already in use: bind
[23:12:59 INFO]: [connected player] Lin_amao (/36.226.55.42:57829) has connected
[23:12:59 INFO]: [server connection] Lin_amao -> MineCandy has connected
[23:13:00 INFO]: [connected player] wuwu0989 (/49.217.174.102:44632) has connected
[23:13:00 INFO]: [server connection] wuwu0989 -> MineCandy has connected
[23:13:02 INFO]: [connected player] Naurto01 (/106.1.117.247:24895) has connected
[23:13:02 INFO]: [server connection] Naurto01 -> MineCandy has connected
`
**Other mods**

**Checklist**

 - [ ] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [ ] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by ishland** [comment]
The ViaVersion issue doesn't seem to be related to raknetify at all. 

The "Address already in use" is because Geyser is running on the server port. Please configure Geyser to use a different port instead.

**Comment by candy999** [comment]
0.1.0+alpha.5.33 devbuild for Velocity 3.2.0 fix it
my Geyser run 19132 port change GS4 query protocol port to 25566 fix raknetify bind 25565 port
raknetify can edit yaml set bind port in the future?

**Comment by ishland** [comment]
> raknetify can edit yaml set bind port in the future?

This feature doesn't make any sense for most of the people because players are connecting just with a different method with the same client.

**Comment by 8MiYile** [comment]
It is recommended that the ViaVersion suite of plug-ins be replaced with a version that supports snapshots or the latest development version
