### ISSUE TITLE
Error bootstrapping raknetify inside wrapped environment

### ISSUE THREAD

**Issue by jacklollz2** [RelativityMC/raknetify#21]
Oracle Linux 8.7 el8
Velocity 3.2.0-SNAPSHOT (git-697d08ba-b216)
raknetify 0.1.0+alpha.5.0
Eclipse Temurin 19.0.1+10
Minecraft Java 1.19.3
```
[21:15:46 ERROR] [raknetify]: Error bootstrapping raknetify inside wrapped environment, running in normal environment instead
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at com.ishland.raknetify.velocity.RaknetifyVelocityPlugin.onProxyInit(RaknetifyVelocityPlugin.java:71) ~[?:?]
        at com.ishland.raknetify.velocity.Lmbda$5.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-216.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.2.0-SNAPSHOT-216.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.2.0-SNAPSHOT-216.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.RuntimeException: Failed to inject velocity packet registry
        at com.ishland.raknetify.velocity.init.VelocityPacketRegistryInjector.inject(VelocityPacketRegistryInjector.java:35) ~[?:?]
        at com.ishland.raknetify.velocity.RaknetifyVelocityLaunchWrapper.launch(RaknetifyVelocityLaunchWrapper.java:31) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        ... 9 more
Caused by: java.lang.IllegalAccessError: class com.ishland.raknetify.velocity.init.VelocityPacketRegistryInjector tried to access protected field com.velocitypowered.proxy.protocol.StateRegistry.clientbound (com.ishland.raknetify.velocity.init.VelocityPacketRegistryInjector is in unnamed module of loader 'raknetify wrapper' @31afb332; com.velocitypowered.proxy.protocol.StateRegistry is in unnamed module of loader 'app')
        at com.ishland.raknetify.velocity.init.VelocityPacketRegistryInjector.inject(VelocityPacketRegistryInjector.java:19) ~[?:?]
        at com.ishland.raknetify.velocity.RaknetifyVelocityLaunchWrapper.launch(RaknetifyVelocityLaunchWrapper.java:31) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        ... 9 more
[21:15:46 ERROR]: Couldn't pass ProxyInitializeEvent to raknetify
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.ishland.raknetify.velocity.RaknetifyVelocityPlugin.onProxyInit(RaknetifyVelocityPlugin.java:81) ~[?:?]
        at com.ishland.raknetify.velocity.Lmbda$5.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-216.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.2.0-SNAPSHOT-216.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.2.0-SNAPSHOT-216.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at com.ishland.raknetify.velocity.RaknetifyVelocityPlugin.onProxyInit(RaknetifyVelocityPlugin.java:79) ~[?:?]
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/IntArrays
        at it.unimi.dsi.fastutil.ints.Int2ObjectArrayMap.<init>(Int2ObjectArrayMap.java:73) ~[velocity-3.2.0-SNAPSHOT-216.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at com.ishland.raknetify.common.data.ProtocolMultiChannelMappings.<init>(ProtocolMultiChannelMappings.java:38) ~[?:?]
        at com.ishland.raknetify.common.data.ProtocolMultiChannelMappings.<clinit>(ProtocolMultiChannelMappings.java:22) ~[?:?]
        at com.ishland.raknetify.velocity.RaknetifyVelocityLaunchWrapper.launch(RaknetifyVelocityLaunchWrapper.java:30) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at com.ishland.raknetify.velocity.RaknetifyVelocityPlugin.onProxyInit(RaknetifyVelocityPlugin.java:79) ~[?:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.ints.IntArrays
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at it.unimi.dsi.fastutil.ints.Int2ObjectArrayMap.<init>(Int2ObjectArrayMap.java:73) ~[velocity-3.2.0-SNAPSHOT-216.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at com.ishland.raknetify.common.data.ProtocolMultiChannelMappings.<init>(ProtocolMultiChannelMappings.java:38) ~[?:?]
        at com.ishland.raknetify.common.data.ProtocolMultiChannelMappings.<clinit>(ProtocolMultiChannelMappings.java:22) ~[?:?]
        at com.ishland.raknetify.velocity.RaknetifyVelocityLaunchWrapper.launch(RaknetifyVelocityLaunchWrapper.java:30) ~[?:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
        at com.ishland.raknetify.velocity.RaknetifyVelocityPlugin.onProxyInit(RaknetifyVelocityPlugin.java:79) ~[?:?]
        ... 7 more
```

**Comment by ishland** [comment]
Try this version and see if it fixes this for you. 
https://modrinth.com/mod/raknetify/version/0.1.0+alpha.5.33+velocity

**Comment by jacklollz2** [comment]
> Try this version and see if it fixes this for you. https://modrinth.com/mod/raknetify/version/0.1.0+alpha.5.33+velocity

Error is gone, however, players connecting are stuck on "Connecting to the server..." then get "connection timed out".

**Comment by ishland** [comment]
Looks like your firewall isn't configured properly. 

> You need to have a UDP port opened at the same port number of your normal server port.

**Comment by jacklollz2** [comment]
> Looks like your firewall isn't configured properly.
> 
> > You need to have a UDP port opened at the same port number of your normal server port.

Already is, both TCP and UDP transport is allowed through, but I will do some aggressive testing

**Comment by jacklollz2** [comment]
Could it be related to TCPShield? I don't think so, as TCPShield seems to be forwarding UDP.

**Comment by ishland** [comment]
It could be related. 

And the issue tracker isn't a good place for this kind of problem. Join our [discord server](https://discord.gg/Kdy8NM5HW4).

**Comment by LittleChest** [comment]
i have the same problem
