### ISSUE TITLE
magic items in the backpack causes disconnected kicking out.

### ISSUE THREAD

**Issue by candy999** [RelativityMC/raknetify#26]
**Describe the bug**
Installing the magic plugin in purpur and obtaining magic items in the backpack causes disconnected kicking out.

**To Reproduce**
1. purpur plugin https://www.spigotmc.org/resources/magic.1056/
2. "/wand" to get magic items
1. open backpack

**Expected behavior**

**Screenshots**
[https://youtu.be/UusuxAP6Hew](https://youtu.be/UusuxAP6Hew)

**Runtime info (please complete the following information):**
 - Minecraft version: 1.19.3
 - Mod version: raknetify-velocity-0.1.0+alpha.5.54-all.jar
 - Mod branch: 
 `[12:29:36 INFO]: Velocity 3.2.0-SNAPSHOT (git-e0e156a4-b228)
[12:29:36 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[12:29:36 INFO]: velocitypowered.com - GitHub`

**Crash reports / logs**
`
[12:10:39 INFO]: [connected player] CandySister (/111.243.21.138:55240) has connected                             
[12:10:39 INFO] [raknetify]: Preventing vanilla compression as streaming compression is enabled                   
[12:10:39 INFO] [raknetify]: Preventing vanilla compression as streaming compression is enabled                   
[12:10:39 INFO] [raknetify]: Raknetify: CandySister logged in via RakNet, mtu 1398                                
[12:10:39 INFO]: [server connection] CandySister -> MineCandy has connected                                       
[12:10:42 ERROR]: [server connection] CandySister -> MineCandy: exception encountered in com.velocitypowered.proxy
.connection.backend.BackendPlaySessionHandler@59304229                                                            
io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: source has multiple backing buffers  
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[velocity-3.2.0-SNAPS
HOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                                   
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[v
elocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[ve
locity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                 
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity
-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                       
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity
-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                       
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[velocity-3.2.0
-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                             
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[v
elocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[ve
locity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                 
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[velocity
-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                       
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[velocity
-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                       
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120) ~[velocity-3.2.0-SNAPS
HOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                                   
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[v
elocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:9
40) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                         
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[velocity
-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                       
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[
velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                               
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020) ~[velocity-3.2.
0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                            
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311) ~[velocity-3.2.0-SNAPSHOT-228.
jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                                           
        at com.velocitypowered.proxy.connection.MinecraftConnection.write(MinecraftConnection.java:220) ~[velocity
-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                       
        at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handleUnknown(ClientPlaySessionHan
dler.java:410) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                              
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:151) ~[ve
locity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                 
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                             
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[veloc
ity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                    
        at com.ishland.raknetify.velocity.connection.RakNetVelocityChannelEventListener.channelRead(RakNetVelocity
ChannelEventListener.java:83) ~[?:?]                                                                              
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                             
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:78) ~[velocit
y-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                      
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61) ~[veloc
ity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                    
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                             
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity
-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                       
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                             
        at com.ishland.raknetify.common.connection.FrameDataBlocker.channelRead(FrameDataBlocker.java:42) ~[?:?]  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                             
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity
-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                       
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[velocity-3.2
.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                           
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                             
        at com.ishland.raknetify.common.connection.MultiChannelingStreamingCompression.channelRead(MultiChanneling
StreamingCompression.java:166) ~[?:?]                                                                             
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                             
        at com.ishland.raknetify.common.connection.MultiChannellingEncryption.channelRead(MultiChannellingEncrypti
on.java:100) ~[?:?]                                                                                               
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) 
~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                             
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[vel
ocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                  
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440
) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                           
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61) ~[velo
city-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                   
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425) ~[velocity
-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                       
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[velocity-3.2.0
-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                             
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[velocity-3
.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                         
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[ve
locity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                 
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SN
APSHOT (git-e0e156a4-b228)]                                                                                       
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity
-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                       
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.2.0-SNAPSHOT-228
.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                                          
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.2.0-
SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                              
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]                                                          
Caused by: java.lang.IllegalArgumentException: source has multiple backing buffers                                
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[velocity-3.2.0-SNAPSHOT-22
8.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                                         
        at com.velocitypowered.natives.compression.JavaVelocityCompressor.deflate(JavaVelocityCompressor.java:86) 
~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                             
        at com.velocitypowered.proxy.protocol.netty.MinecraftCompressorAndLengthEncoder.handleCompressed(Minecraft
CompressorAndLengthEncoder.java:66) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]         
        at com.velocitypowered.proxy.protocol.netty.MinecraftCompressorAndLengthEncoder.encode(MinecraftCompressor
AndLengthEncoder.java:52) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                   
        at com.velocitypowered.proxy.protocol.netty.MinecraftCompressorAndLengthEncoder.encode(MinecraftCompressor
AndLengthEncoder.java:33) ~[velocity-3.2.0-SNAPSHOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                   
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[velocity-3.2.0-SNAPS
HOT-228.jar:3.2.0-SNAPSHOT (git-e0e156a4-b228)]                                                                   
        ... 65 more                                                                                               
[12:10:42 ERROR]: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: source has multiple
 backing buffers                                                                                                  
[12:10:42 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)       
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerConte
xt.java:881)                                                                                                      
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContex
t.java:863)                                                                                                       
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java
:968)                                                                                                             
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java
:856)                                                                                                             
[12:10:42 ERROR]:       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerConte
xt.java:881)                                                                                                      
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContex
t.java:863)                                                                                                       
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java
:968)                                                                                                             
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java
:856)                                                                                                             
[12:10:42 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:120)       
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerConte
xt.java:881)                                                                                                      
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandl
erContext.java:940)                                                                                               
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java
:966)                                                                                                             
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerCont
ext.java:934)                                                                                                     
[12:10:42 ERROR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)               
[12:10:42 ERROR]:       at com.velocitypowered.proxy.connection.MinecraftConnection.write(MinecraftConnection.java
:220)                                                                                                             
[12:10:42 ERROR]:       at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handleUnknown(Clie
ntPlaySessionHandler.java:410)                                                                                    
[12:10:42 ERROR]:       at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnectio
n.java:151)                                                                                                       
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:444)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:420)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCo
ntext.java:412)                                                                                                   
[12:10:42 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.
java:93)                                                                                                          
[12:10:42 ERROR]:       at raknetify wrapper//com.ishland.raknetify.velocity.connection.RakNetVelocityChannelEvent
Listener.channelRead(RakNetVelocityChannelEventListener.java:83)                                                  
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:442)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:420)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCo
ntext.java:412)                                                                                                   
[12:10:42 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.ja
va:78)                                                                                                            
[12:10:42 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.
java:61)                                                                                                          
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:444)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:420)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCo
ntext.java:412)                                                                                                   
[12:10:42 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java
:103)                                                                                                             
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:444)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:420)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCo
ntext.java:412)                                                                                                   
[12:10:42 ERROR]:       at raknetify wrapper//com.ishland.raknetify.common.connection.FrameDataBlocker.channelRead
(FrameDataBlocker.java:42)                                                                                        
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:444)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:420)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCo
ntext.java:412)                                                                                                   
[12:10:42 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java
:103)                                                                                                             
[12:10:42 ERROR]:       at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111
)                                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:442)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:420)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCo
ntext.java:412)                                                                                                   
[12:10:42 ERROR]:       at raknetify wrapper//com.ishland.raknetify.common.connection.MultiChannelingStreamingComp
ression.channelRead(MultiChannelingStreamingCompression.java:166)                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:442)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:420)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCo
ntext.java:412)                                                                                                   
[12:10:42 ERROR]:       at raknetify wrapper//com.ishland.raknetify.common.connection.MultiChannellingEncryption.c
hannelRead(MultiChannellingEncryption.java:100)                                                                   
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:442)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:420)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerCo
ntext.java:412)                                                                                                   
[12:10:42 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.
java:1410)                                                                                                        
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandler
Context.java:440)                                                                                                 
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext
.java:61)                                                                                                         
[12:10:42 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java
:425)                                                                                                             
[12:10:42 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) 
[12:10:42 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:1
67)                                                                                                               
[12:10:42 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecuto
r.java:470)                                                                                                       
[12:10:42 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)                           
[12:10:42 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java
:997)                                                                                                             
[12:10:42 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)              
[12:10:42 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)  
[12:10:42 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:1589)                                       
[12:10:42 ERROR]: Caused by: java.lang.IllegalArgumentException: source has multiple backing buffers              
[12:10:42 ERROR]:       at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)             
[12:10:42 ERROR]:       at com.velocitypowered.natives.compression.JavaVelocityCompressor.deflate(JavaVelocityComp
ressor.java:86)                                                                                                   
[12:10:42 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftCompressorAndLengthEncoder.handleComp
ressed(MinecraftCompressorAndLengthEncoder.java:66)                                                               
[12:10:42 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftCompressorAndLengthEncoder.encode(Min
ecraftCompressorAndLengthEncoder.java:52)                                                                         
[12:10:42 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftCompressorAndLengthEncoder.encode(Min
ecraftCompressorAndLengthEncoder.java:33)                                                                         
[12:10:42 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)       
[12:10:42 ERROR]:       ... 65 more                                                                               
[12:10:42 INFO]: frame-decoder: com.velocitypowered.proxy.protocol.netty.MinecraftVarintFrameDecoder              
[12:10:42 INFO]: read-timeout: io.netty.handler.timeout.ReadTimeoutHandler                                        
[12:10:42 INFO]: compression-decoder: com.velocitypowered.proxy.protocol.netty.MinecraftCompressDecoder           
[12:10:42 INFO]: via-decoder: com.viaversion.viaversion.velocity.handlers.VelocityDecodeHandler                   
[12:10:42 INFO]: minecraft-decoder: com.velocitypowered.proxy.protocol.netty.MinecraftDecoder                     
[12:10:42 INFO]: flow-handler: com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler                     
[12:10:42 INFO]: compression-encoder: com.velocitypowered.proxy.protocol.netty.MinecraftCompressorAndLengthEncoder
[12:10:42 INFO]: via-encoder: com.viaversion.viaversion.velocity.handlers.VelocityEncodeHandler                   
[12:10:42 INFO]: minecraft-encoder: com.velocitypowered.proxy.protocol.netty.MinecraftEncoder                     
[12:10:42 INFO]: raknetify-bungee-downstream-event-listener: com.ishland.raknetify.velocity.connection.RakNetVeloc
ityServerChannelEventListener                                                                                     
[12:10:42 INFO]: handler: com.velocitypowered.proxy.connection.MinecraftConnection                                
[12:10:42 INFO]: [server connection] CandySister -> MineCandy has disconnected                                    
[12:10:42 INFO]: [server connection] CandySister -> Lobby has connected                                           
`
**Other mods**
![image](https://user-images.githubusercontent.com/2743971/220009811-21c587be-c12e-4c39-b381-54f5861c1439.png)
**Checklist**

 - [x] I am using the official version of the mod. 
 - [x] I tried the latest development version but the issue persists. 
 - [x] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by ishland** [comment]
Try reproduce with latest devbuild and see if it still happens.
