### ISSUE TITLE
1.20.1 Unable to connect to server

### ISSUE THREAD

**Issue by exalented** [RelativityMC/raknetify#38]
**Describe the bug**
`connection timed out` on client when using `raknet;` prefix

**To Reproduce**
1. Attempt to connect using raknet
2. See error

**Expected behavior**
Client logs in and is in-game.

**Runtime info:**
 - OS: Arch kernel server (6.4.1-arch1-1)
   - Docker: Docker version 24.0.2, build cb74dfcd85
     - image: eclipse-temurin:17-jre-alpine
     - ports:
       - 25565:25565          #minecraft
       - 25565:25565/udp #Raknet
       - 8101:8100              #bluemap
 - OS: Arch kernel client (6.4.9-arch1-1) prismlauncher 7.2
   - local/jre17-openjdk 17.0.8.u7-1
 - Minecraft version: 1.20.1
 - Mod version: raknetify-fabric-0.1.0+alpha.5.93-all.jar from modrinth
<details>
  <summary>Server reports / logs</summary>
  
  ```
[00:09:51] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 2 override(s) found
[00:09:51] [main/INFO]: Successfully started async appender with [ServerGuiConsole, SysOut, File]
[00:09:51] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[00:09:51] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me, vmp]) disables it and children
[00:09:54] [main/INFO]: Mixing common.MixinFriendlyByteBuf from mixins/common/nochatreports.mixins.json into net.minecraft.class_2540
[00:09:54] [main/INFO]: Renaming synthetic method lambda$onWriteJsonWithCodec$1(Ljava/lang/Object;Ljava/lang/String;)Lio/netty/handler/codec/EncoderException; to md23f453$nochatreports$lambda$onWriteJsonWithCodec$1$0 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf from mod nochatreports
[00:09:54] [main/INFO]: Renaming synthetic method lambda$onReadJsonWithCodec$0(Ljava/lang/String;)Lio/netty/handler/codec/DecoderException; to md23f453$nochatreports$lambda$onReadJsonWithCodec$0$1 in mixins/common/nochatreports.mixins.json:common.MixinFriendlyByteBuf from mod nochatreports
[00:09:58] [main/INFO]: Mixing server.MixinServerGamePacketListenerImpl from mixins/common/nochatreports.mixins.json into net.minecraft.class_3244
[00:09:58] [main/WARN]: Method overwrite conflict for getConnection in fabric-networking-api-v1.mixins.json:accessor.ServerPlayNetworkHandlerAccessor from mod fabric-networking-api-v1, previously written by carpet.mixins.ServerGamePacketListenerImpl_coreMixin. Skipping method.
[00:09:59] [main/INFO]: Loading Collective version 6.65.
[00:09:59] [main/INFO]: KONNICHIWA ZA WARUDO!
[00:09:59] [main/INFO]: Default JVM text encoding is: UTF-8
[00:09:59] [main/INFO]: Reading config file NoChatReports/NCR-Common.json...
[00:09:59] [main/INFO]: Writing config file NoChatReports/NCR-Common.json...
[00:09:59] [Via-Mappingloader-0/INFO]: Loading block connection mappings ...
[00:10:00] [Via-Mappingloader-0/INFO]: Using FastUtil Long2ObjectOpenHashMap for block connections
[00:10:00] [main/INFO]: Loading translations...
[00:10:00] [main/INFO]: Registering protocols...
[00:10:00] [main/INFO]: ViaVersion detected server version: 1.20/1.20.1 (763)
[00:10:00] [ViaFabric-2/INFO]: Finished mapping loading, shutting down loader executor!
[00:10:00] [main/INFO]: Mixing server.MixinServerboundChatSessionUpdatePacket from mixins/common/nochatreports.mixins.json into net.minecraft.class_7861
[00:10:00] [main/INFO]: Mixing server.MixinServerboundChatCommandPacket from mixins/common/nochatreports.mixins.json into net.minecraft.class_7472
[00:10:00] [main/INFO]: Mixing server.MixinServerboundChatPacket from mixins/common/nochatreports.mixins.json into net.minecraft.class_2797
[00:10:01] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:10:01] [ViaFabric-0/WARN]: You are running a newer version of the plugin than is released!
[00:10:03] [main/INFO]: Loaded 7 recipes
[00:10:03] [main/INFO]: Loaded 1271 advancements
[00:10:04] [main/INFO]: Mixing server.MixinDedicatedServer from mixins/common/nochatreports.mixins.json into net.minecraft.class_3176
[00:10:04] [main/INFO]: Mixing server.MixinPlayerList from mixins/common/nochatreports.mixins.json into net.minecraft.class_3324
[00:10:04] [main/INFO]: Applied 0 biome modifications to 0 of 164 new biomes in 2.172 ms
[00:10:04] [Server thread/INFO]: Starting minecraft server version 1.20.1
[00:10:04] [Server thread/INFO]: Loading properties
[00:10:04] [Server thread/INFO]: Default game type: SURVIVAL
[00:10:04] [Server thread/INFO]: Generating keypair
[00:10:04] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:25565
[00:10:04] [Server thread/INFO]: Using epoll channel type
[00:10:04] [Server thread/INFO]: Preparing level "world"
[00:10:04] [Server thread/INFO]: Enforcing safe world random access
[00:10:05] [Server thread/INFO]: Changing watch distance to 6
[00:10:05] [Server thread/INFO]: Changing watch distance to 6
[00:10:05] [Server thread/INFO]: Changing watch distance to 6
[00:10:05] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[00:10:06] [Worker-Main-15/INFO]: Preparing spawn area: 0%
[00:10:06] [Worker-Main-15/INFO]: Preparing spawn area: 0%
[00:10:06] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[00:10:07] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[00:10:08] [Worker-Main-10/INFO]: Preparing spawn area: 0%
[00:10:08] [Worker-Main-15/INFO]: Preparing spawn area: 0%
[00:10:08] [Worker-Main-15/INFO]: Preparing spawn area: 1%
[00:10:09] [Worker-Main-1/INFO]: Preparing spawn area: 4%
[00:10:09] [Worker-Main-15/INFO]: Preparing spawn area: 29%
[00:10:10] [Worker-Main-4/INFO]: Preparing spawn area: 61%
[00:10:10] [Worker-Main-4/INFO]: Preparing spawn area: 93%
[00:10:10] [Server thread/INFO]: Time elapsed: 5167 ms
[00:10:10] [Server thread/INFO]: Done (6.456s)! For help, type "help"
[00:10:10] [BlueMap-Plugin-Loading/INFO]: Loading BlueMap...
[00:10:11] [BlueMap-Plugin-Loading/INFO]: Loading resources...
[00:10:11] [Server thread/INFO]: UDP server is started on /0.0.0.0:25565
[00:10:11] [Server thread/INFO]: Mixing common.MixinServerStatus from mixins/common/nochatreports.mixins.json into net.minecraft.class_2926
[00:10:11] [BlueMap-Plugin-Loading/INFO]: Loading textures...
[00:10:12] [BlueMap-Plugin-Loading/INFO]: Baking resources...
[00:10:12] [BlueMap-Plugin-Loading/INFO]: Resources loaded.
[00:10:12] [BlueMap-Plugin-Loading/INFO]: Loading world '...' (/server/world/DIM-1)...
[00:10:12] [BlueMap-Plugin-Loading/INFO]: Initializing Storage: 'file' (Type: FILE)
[00:10:12] [BlueMap-Plugin-Loading/INFO]: Loading map 'Nether'...
[00:10:12] [BlueMap-Plugin-Loading/INFO]: Loading world '...' (/server/world/DIM1)...
[00:10:12] [BlueMap-Plugin-Loading/INFO]: Loading map 'End'...
[00:10:12] [BlueMap-Plugin-Loading/INFO]: Loading world '...' (/server/world)...
[00:10:12] [BlueMap-Plugin-Loading/INFO]: Loading map 'Overworld'...
[00:10:13] [BlueMap-Plugin-Loading/INFO]: WebServer bound to: /0.0.0.0:8100
[00:10:13] [Thread-14/INFO]: WebServer started.
[00:10:13] [BlueMap-Plugin-Loading/INFO]: BlueMap loaded!
  ```
</details>
<details>
  <summary>Client reports / logs</summary>
  
  ```
[17:11:44] [Render thread/INFO]: Connecting to raknet;ip.local, 25565
[17:11:50] [Netty Epoll Client IO #1/WARN]: An exception 'java.lang.NoSuchFieldError: field_45667' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.timeout.ReadTimeoutException: null
[17:12:14] [Server Connector #2/ERROR]: Couldn't connect to server
io.netty.channel.ConnectTimeoutException: connection timed out
	at network.ycc.raknet.pipeline.AbstractConnectionInitializer.doTimeout(AbstractConnectionInitializer.java:71) ~[raknetify-fabric-0.1.0+alpha.5.93-all.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:12:56] [Render thread/INFO]: emissive suffixes loaded: {_e}
[17:12:56] [Render thread/INFO]: Connecting to raknetl;ip.local, 25565
[17:13:26] [Server Connector #3/ERROR]: Couldn't connect to server
io.netty.channel.ConnectTimeoutException: connection timed out
	at network.ycc.raknet.pipeline.AbstractConnectionInitializer.doTimeout(AbstractConnectionInitializer.java:71) ~[raknetify-fabric-0.1.0+alpha.5.93-all.jar:?]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406) ~[netty-transport-classes-epoll-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
  ```
</details>
<details>
  <summary>Other client mods</summary>
  
  ```
[main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[main/INFO]: Loading 161 mods:
	- animatica 0.6+1.20
	- antighost 1.20-fabric0.83.0-1.1.5
	   \-- crowdin-translate 1.4+1.19.3
	- bedrodium 0.2.2
	- betterbeds 1.3.0
	- c2me 0.2.0+alpha.10.97
	   |-- c2me-base 0.2.0+alpha.10.97
	   |-- c2me-client-uncapvd 0.2.0+alpha.10.97
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.10.97
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.10.97
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.10.97
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.10.97
	   |-- c2me-notickvd 0.2.0+alpha.10.97
	   |-- c2me-opts-allocs 0.2.0+alpha.10.97
	   |-- c2me-opts-chunk-access 0.2.0+alpha.10.97
	   |-- c2me-opts-chunkio 0.2.0+alpha.10.97
	   |-- c2me-opts-math 0.2.0+alpha.10.97
	   |-- c2me-opts-scheduling 0.2.0+alpha.10.97
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.10.97
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.10.97
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.10.97
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.10.97
	   |-- c2me-server-utils 0.2.0+alpha.10.97
	   |-- c2me-threading-chunkio 0.2.0+alpha.10.97
	   |-- c2me-threading-lighting 0.2.0+alpha.10.97
	   |-- c2me-threading-worldgen 0.2.0+alpha.10.97
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- completeconfig 2.5.0
	   |-- completeconfig-base 2.5.0
	   |-- completeconfig-gui-cloth 2.5.0
	   \-- completeconfig-gui-yacl 2.5.0
	- cull-less-leaves 1.2.0
	- entity_model_features 0.2.13
	- entity_texture_features 4.5.0
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.2-mc1.20
	- exordium 1.1.3.1-mc1.20.1
	- fabric-api 0.87.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.9+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.2.2+1e61dba177
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.10+23d9108177
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.39+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.43+9e7660c677
	   |-- fabric-message-api-v1 5.1.7+3265161977
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.1+6beca84877
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.1.2+6bdb2ed077
	   |-- fabric-renderer-indigo 1.4.2+6bdb2ed077
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.34+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.0+cdf060b277
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabricloader 0.14.21
	- fallingleaves 1.15.2+1.20.1
	- fastload 3.4.0
	   |-- conditional-mixin 0.3.2
	   |-- fastload-119-0-1-2-compat 3.4.0
	   |-- fastload-1193-compat 3.4.0
	   |-- fastload-1194-compat 3.4.0
	   \-- fastload_fapi_forward 1.0.2
	- ferritecore 6.0.0
	- immediatelyfast 1.1.27+1.20.1
	   |-- com_github_llamalad7_mixinextras 0.2.0-beta.9
	   \-- net_lenni0451_reflect 1.2.1
	- iris 1.6.5
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- languagereload 1.5.8+1.20.1
	- lazydfu 0.1.3
	- libjf 3.12.0
	   |-- libjf-base 3.12.0
	   |-- libjf-config-commands-v1 3.12.0
	   |    \-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- libjf-config-core-v1 3.12.0
	   |-- libjf-config-reflect-v1 3.12.0
	   |-- libjf-config-ui-tiny-v1 3.12.0
	   |-- libjf-data-manipulation-v0 3.12.0
	   |-- libjf-data-v0 3.12.0
	   |-- libjf-translate-v1 3.12.0
	   |-- libjf-unsafe-v0 3.12.0
	   \-- libjf-web-v0 3.12.0
	        \-- fabric-command-api-v2 2.2.12+b3afc78b77
	- litematica 0.15.3
	- lithium 0.11.2
	- malilib 0.16.1
	- meteor-client 0.5.4-1874
	   \-- baritone-meteor 1.20.1-SNAPSHOT
	- meteor-rejects 0.3
	   \-- seedcrackerx-api 2.10.1
	- meteorist 1.5
	- minecraft 1.20.1
	- modmenu 7.2.1
	- no-telemetry 1.7.0
	- nochatreports 1.20.1-v2.2.2
	- presencefootsteps 1.9.0
	   \-- kirin 1.15.0
	- raknetify 0.1.0+alpha.5.93
	- reeses-sodium-options 1.6.4+mc1.20.1-build.94
	- respackopts 4.3.1
	   \-- io_gitlab_jfronny_muscript 1.3-SNAPSHOT
	- servercountryflags 1.8.1
	- serverpingerfixer 1.0.1
	- skinlayers 1.5.4-mc1.20.1
	- skiptransitions 1.3.3+mc1.20
	- sodium 0.5.0
	- sodium-extra 0.5.0+mc1.20.1-build.111
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- tweakeroo 0.17.1
	- uiutils 1.3.1
	- viafabricplus 2.8.2
	- yet_another_config_lib_v3 3.1.0+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   \-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
  ```
</details>

**Checklist**
 - [x] I am using the official version of the mod. 
 - [X] I tried the latest development version but the issue persists. 
 - [X] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**
Perhaps I'm not fully understanding how to get this setup. *Please let me know if I may be missing something or how I can test in a better way*.
The server info is able to be displayed fine when using the `raknet;` prefix on the client.
The fact the server reports `UDP server is started on /0.0.0.0:25565` lets me know the raknet server should be working correctly.

**Comment by ishland** [comment]
> The fact the server reports UDP server is started on /0.0.0.0:25565 lets me know the raknet server should be working correctly.

Raknetify should show `Starting raknetify server on /....` rather than that. Also you might have some mods that interferes with the server ping so it still shows as online.

**Comment by Casmin7** [comment]
Same thing here, although i get the `Starting raknetify server on /....`

**Comment by exalented** [comment]
Only *after* creating the issue here I find out the server hadn't loaded the plugin. Sorry for the issue spam. Thanks for your help and for the great plugins ishland.
